project_id = "gsnqucupjpdlfeqpbjup"

[functions.sitemap]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.robokassa-init]
verify_jwt = false

[functions.robokassa-callback]
verify_jwt = false
